# Generated by Django 2.2 on 2019-04-21 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='include_author',
        ),
    ]
