# Generated by Django 2.2 on 2019-06-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calen', '0002_shareablelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='data',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
